-- Task 4 Starts Here
 
 -- 1.Query to find which customer have not placed any order
 select * from Customers where CustomerID not in (select CustomerID from Orders);
 
 -- 2.Total number number of products available for sale
 select  count(ProductID) as Total_no_of_products_sales from inventory where QuantityInStock > 0;
 
 -- 3.Query to generate the total revenue generated by the techshop
 select sum(TotalAmount) as Revenue_generated from Orders ;
 
 -- 4.Query to list avg quantity ordered for a specific category
 
 select * from Products;
 
 select * from OrderDetails;
 
select avg(OrderDetails.Quantity) as avg_order ,Category_table.Category from 
 (
 select ProductID , ProductName ,Category from Products where Category in('Computer')
 ) 
 as Category_table join OrderDetails on Category_table.ProductID = OrderDetails.ProductID ;
 
 -- 5.Query to generate total revenue generated by a specific customer using customerID
 
 select Customers.FirstName,Customers.LastName, Orders.CustomerID , sum(Orders.TotalAmount) as revenue_gen
 from 
 Orders
 join Customers on Orders.CustomerID = Customers.CustomerID where Orders.CustomerID = 'CUST010'  group by Orders.CustomerID;

select * from Orders;

-- 6.Query to list down all the customers based on the number of orders placed

select Customers.FirstName,Customers.LastName,count_table.CustomerID,count_table.count from
 ( 
 select Orders.CustomerID, count(Orders.OrderID) as count from Orders group by CustomerID 
 )
 as count_table join Customers on count_table.CustomerID = Customers.CustomerID order by count_table.count desc limit 1; 

 
 -- 7. Query to find the most popular product category , which is the one with the highest total quantity ordered across all orders 
 
 select Products.Category  , sum(OrderDetails.Quantity) as sum_of_orders 
 from
 Products
 join
 OrderDetails
 on Products.ProductID = OrderDetails.ProductID
 group by Products.Category
 order by sum_of_orders
 desc limit 1;


-- 8.Query to find out the customer who spend the most money (Highest revenue) with their name and Total money spend
select Customers.CustomerID,Customers.FirstName,Customers.LastName,customer_table.Total_spend from 
 (
 select CustomerID, sum(TotalAmount) as Total_spend from Orders group by CustomerID 
 )
 as customer_table right join Customers on customer_table.CustomerID = Customers.CustomerID order by customer_table.Total_spend desc limit 1;
 
 -- 9.Query to list down all the customers with avg order values
 
 select Customers.CustomerID,Customers.FirstName,Customers.LastName,customer_table.avg_order_value from
 (
 select CustomerID, avg(TotalAmount) as avg_order_value from Orders group by CustomerID
 )
 as customer_table right join Customers on customer_table.CustomerID = Customers.CustomerID ;
 
 -- 10.Query to list down all the customers with total no of orders they have made
 
 select Customers.CustomerID,Customers.FirstName,Customers.LastName,customer_table.no_of_orders from
 (
 select CustomerID, count(Orders.OrderID) as no_of_orders from Orders group by CustomerID
 )
 as customer_table right join Customers on customer_table.CustomerID = Customers.CustomerID ;
 
